#!/usr/bin/env python3
"""Translate the 117 hset_* strings into the 10 non-English locales.

Run from the repo root. Each locale file gets a fresh block appended before
</resources>; existing content is left untouched.
"""
import re
import xml.dom.minidom
import sys

REPO = "/Users/heavens3/deepseek/deepseek-harness-mobile"
BASE = f"{REPO}/app/src/main/res/values/strings.xml"

# ---------------------------------------------------------------------------
# The 117 keys, in the order they appear in the base file.
# ---------------------------------------------------------------------------
KEYS = [
    "hset_title","hset_entry","hset_tab_general","hset_tab_models","hset_tab_plugins","hset_tab_presets",
    "hset_refused_banner","hset_unsupported_banner","hset_readonly_banner","hset_edit_available",
    "hset_load_error","hset_retry","hset_saved","hset_removed","hset_save_failed","hset_conflict","hset_not_connected",
    "hset_general_preset_title","hset_general_preset_hint","hset_general_permission_title","hset_general_permission_hint",
    "hset_general_permission_no_session","hset_general_permission_unknown","hset_general_locale_title","hset_general_locale_system",
    "hset_general_locale_en","hset_general_locale_zh","hset_general_theme_title","hset_general_theme_light","hset_general_theme_dark",
    "hset_general_theme_system","hset_general_open_document","hset_general_open_document_hint","hset_general_document_opened",
    "hset_general_document_unavailable",
    "hset_models_empty","hset_models_active","hset_models_custom","hset_models_add_provider","hset_models_add_custom",
    "hset_models_edit","hset_models_remove","hset_models_remove_model","hset_models_remove_confirm_title","hset_models_remove_confirm",
    "hset_models_key_label","hset_models_key_configured","hset_models_key_missing","hset_models_key_hint","hset_models_base_url",
    "hset_models_api_protocol","hset_models_display_name","hset_models_custom_route","hset_models_models_label","hset_models_models_hint_empty",
    "hset_models_built_in_catalog","hset_models_count","hset_models_add_model","hset_models_model_id","hset_models_model_name",
    "hset_models_model_context","hset_models_model_max_tokens","hset_models_discover","hset_models_discover_title","hset_models_discover_hint",
    "hset_models_discover_fetch","hset_models_discover_apply","hset_models_discover_failed","hset_models_discover_none","hset_models_advanced",
    "hset_models_unknown_ns",
    "hset_plugins_configurable","hset_plugins_inventory","hset_plugins_card_shell","hset_plugins_shell_timeout","hset_plugins_shell_max_output",
    "hset_plugins_card_agent_loop","hset_plugins_agent_loop_max_parallel","hset_plugins_card_web_search","hset_plugins_web_search_base_url",
    "hset_plugins_web_search_max_uses","hset_plugins_base_value","hset_plugins_other","hset_plugins_inventory_search","hset_plugins_inventory_empty",
    "hset_plugins_disabled",
    "hset_presets_hint","hset_preset_empty","hset_preset_default","hset_preset_trust_system","hset_preset_trust_user","hset_preset_broken",
    "hset_preset_view","hset_preset_set_default","hset_preset_copy","hset_preset_copy_title","hset_preset_copy_hint","hset_preset_copy_id",
    "hset_preset_copy_name","hset_preset_id_invalid","hset_preset_delete_title","hset_preset_delete_confirm","hset_preset_default_saved",
    "hset_preset_copied","hset_preset_deleted",
    "hset_val_route_invalid","hset_val_route_taken","hset_val_base_url_required","hset_val_models_required","hset_val_model_prefix",
    "hset_val_model_id_required","hset_val_model_id_duplicate","hset_val_model_name","hset_val_model_context","hset_val_model_max_tokens",
    "hset_val_api_key_blank","hset_val_api_key_format",
]
assert len(KEYS) == 117, len(KEYS)

# ---------------------------------------------------------------------------
# Translations. Placeholders %1$s / %1$d are preserved verbatim.
# ---------------------------------------------------------------------------
T = {}

T["es"] = {
 "hset_title":"Ajustes del harness","hset_entry":"Ajustes del harness","hset_tab_general":"General","hset_tab_models":"Modelos","hset_tab_plugins":"Complementos","hset_tab_presets":"Preajustes de agente",
 "hset_refused_banner":"Este harness no concedió acceso remoto a los ajustes. Inícialo con --allow-privileged-remote para editar ajustes desde este dispositivo.","hset_unsupported_banner":"Esta compilación del harness no expone el plano de ajustes.","hset_readonly_banner":"La edición de ajustes no está disponible; se muestran valores de solo lectura.","hset_edit_available":"La edición de ajustes está disponible en este harness.",
 "hset_load_error":"No se pudieron leer los ajustes del harness: %1$s","hset_retry":"Reintentar","hset_saved":"Guardado.","hset_removed":"Eliminado.","hset_save_failed":"Error al guardar: %1$s","hset_conflict":"Los ajustes cambiaron mientras tanto. Se recargaron los valores más recientes; reintenta.","hset_not_connected":"Sin conexión al harness.",
 "hset_general_preset_title":"Preajuste de agente","hset_general_preset_hint":"Se aplica a las sesiones iniciadas desde ahora.","hset_general_permission_title":"Permisos","hset_general_permission_hint":"Modo de permisos predeterminado para nuevas sesiones.","hset_general_permission_no_session":"Sin sesión abierta","hset_general_permission_unknown":"Desconocido","hset_general_locale_title":"Idioma (interfaz web)","hset_general_locale_system":"Sistema","hset_general_locale_en":"Inglés","hset_general_locale_zh":"Chino","hset_general_theme_title":"Apariencia (interfaz web)","hset_general_theme_light":"Claro","hset_general_theme_dark":"Oscuro","hset_general_theme_system":"Sistema","hset_general_open_document":"Abrir el documento de ajustes","hset_general_open_document_hint":"Abre el documento de ajustes del usuario en el equipo del harness.","hset_general_document_opened":"Documento de ajustes abierto en el host.","hset_general_document_unavailable":"Esta instalación no puede abrir el documento de ajustes.",
 "hset_models_empty":"No hay proveedores configurables en esta compilación del harness.","hset_models_active":"Activo","hset_models_custom":"Personalizado","hset_models_add_provider":"Añadir proveedor","hset_models_add_custom":"Añadir proveedor personalizado","hset_models_edit":"Editar","hset_models_remove":"Quitar","hset_models_remove_model":"Quitar modelo","hset_models_remove_confirm_title":"¿Quitar %1$s?","hset_models_remove_confirm":"Esto elimina la configuración del proveedor de los ajustes del harness.","hset_models_key_label":"Clave API","hset_models_key_configured":"Configurada","hset_models_key_missing":"Sin configurar","hset_models_key_hint":"Déjalo en blanco para conservar la clave guardada. El valor solo se escribe y nunca se muestra de nuevo. Se guarda como %1$s.","hset_models_base_url":"URL base","hset_models_api_protocol":"Protocolo","hset_models_display_name":"Nombre para mostrar","hset_models_custom_route":"ID de ruta","hset_models_models_label":"Modelos","hset_models_models_hint_empty":"Sin catálogo personalizado: se usa el catálogo integrado.","hset_models_built_in_catalog":"Catálogo integrado","hset_models_count":"%1$d modelos","hset_models_add_model":"Añadir modelo","hset_models_model_id":"ID del modelo","hset_models_model_name":"Nombre","hset_models_model_context":"Ventana de contexto","hset_models_model_max_tokens":"Máx. de tokens","hset_models_discover":"Detectar modelos","hset_models_discover_title":"Detectar modelos","hset_models_discover_hint":"El harness consulta a este punto final su lista de modelos. No se envía al punto final nada más que la URL base y la clave de este borrador.","hset_models_discover_fetch":"Obtener","hset_models_discover_apply":"Usar %1$d modelos seleccionados","hset_models_discover_failed":"Error en la detección: %1$s","hset_models_discover_none":"El punto final no devolvió modelos.","hset_models_advanced":"Campos avanzados (solo lectura)","hset_models_unknown_ns":"Este proveedor lo configura una sección que esta app no edita: %1$s",
 "hset_plugins_configurable":"Configurables","hset_plugins_inventory":"Inventario","hset_plugins_card_shell":"Shell","hset_plugins_shell_timeout":"Tiempo de espera del comando (ms)","hset_plugins_shell_max_output":"Salida máxima (bytes)","hset_plugins_card_agent_loop":"Bucle del agente","hset_plugins_agent_loop_max_parallel":"Máx. de llamadas de herramienta en paralelo","hset_plugins_card_web_search":"Búsqueda web (DeepSeek)","hset_plugins_web_search_base_url":"URL base","hset_plugins_web_search_max_uses":"Máx. de usos","hset_plugins_base_value":"Predeterminado: %1$s","hset_plugins_other":"Otros ajustes (solo lectura)","hset_plugins_inventory_search":"Buscar complementos","hset_plugins_inventory_empty":"No hay entradas de complementos.","hset_plugins_disabled":"Deshabilitado",
 "hset_presets_hint":"Los preajustes de agente configuran con qué modelo y prompt de sistema inician las nuevas sesiones.","hset_preset_empty":"No hay preajustes de agente.","hset_preset_default":"Predeterminado","hset_preset_trust_system":"Sistema","hset_preset_trust_user":"Usuario","hset_preset_broken":"Roto: %1$s","hset_preset_view":"Ver código fuente","hset_preset_set_default":"Establecer como predeterminado","hset_preset_copy":"Copiar…","hset_preset_copy_title":"Copiar preajuste","hset_preset_copy_hint":"Copia el contenido del preajuste de origen en un nuevo preajuste de usuario.","hset_preset_copy_id":"Nuevo ID de preajuste","hset_preset_copy_name":"Nombre para mostrar (opcional)","hset_preset_id_invalid":"Los IDs de preajuste usan minúsculas, dígitos y guiones, y empiezan con una letra o dígito.","hset_preset_delete_title":"¿Eliminar %1$s?","hset_preset_delete_confirm":"Esto elimina el preajuste. Las sesiones que lo usan no se ven afectadas.","hset_preset_default_saved":"Preajuste predeterminado actualizado.","hset_preset_copied":"Preajuste creado.","hset_preset_deleted":"Preajuste eliminado.",
 "hset_val_route_invalid":"Los IDs de ruta usan minúsculas, dígitos y guiones, y empiezan con una letra.","hset_val_route_taken":"Esa ruta ya existe.","hset_val_base_url_required":"La URL base es obligatoria.","hset_val_models_required":"Se requiere al menos un modelo.","hset_val_model_prefix":"Modelo %1$d: %2$s","hset_val_model_id_required":"el ID del modelo es obligatorio.","hset_val_model_id_duplicate":"ID de modelo duplicado.","hset_val_model_name":"el nombre no puede estar en blanco.","hset_val_model_context":"la ventana de contexto debe ser un número entero positivo.","hset_val_model_max_tokens":"el máximo de tokens debe ser un número entero positivo.","hset_val_api_key_blank":"El campo de la clave contiene solo espacios.","hset_val_api_key_format":"La clave parece envuelta o pegada de una línea de entorno. Pega la clave en bruto.",
}

T["fr"] = {
 "hset_title":"Réglages du harness","hset_entry":"Réglages du harness","hset_tab_general":"Général","hset_tab_models":"Modèles","hset_tab_plugins":"Extensions","hset_tab_presets":"Préréglages d'agent",
 "hset_refused_banner":"Ce harness n'a pas accordé l'accès distant aux réglages. Démarrez-le avec --allow-privileged-remote pour modifier les réglages depuis cet appareil.","hset_unsupported_banner":"Cette version du harness n'expose pas le plan de réglages.","hset_readonly_banner":"La modification des réglages n'est pas disponible ; des valeurs en lecture seule sont affichées.","hset_edit_available":"La modification des réglages est disponible sur ce harness.",
 "hset_load_error":"Impossible de lire les réglages du harness : %1$s","hset_retry":"Réessayer","hset_saved":"Enregistré.","hset_removed":"Supprimé.","hset_save_failed":"Échec de l'enregistrement : %1$s","hset_conflict":"Les réglages ont changé entre-temps. Les valeurs les plus récentes ont été rechargées ; réessayez.","hset_not_connected":"Non connecté au harness.",
 "hset_general_preset_title":"Préréglage d'agent","hset_general_preset_hint":"S'applique aux sessions démarrées à partir de maintenant.","hset_general_permission_title":"Autorisations","hset_general_permission_hint":"Mode d'autorisation par défaut pour les nouvelles sessions.","hset_general_permission_no_session":"Aucune session ouverte","hset_general_permission_unknown":"Inconnu","hset_general_locale_title":"Langue (interface web)","hset_general_locale_system":"Système","hset_general_locale_en":"Anglais","hset_general_locale_zh":"Chinois","hset_general_theme_title":"Apparence (interface web)","hset_general_theme_light":"Clair","hset_general_theme_dark":"Sombre","hset_general_theme_system":"Système","hset_general_open_document":"Ouvrir le document de réglages","hset_general_open_document_hint":"Ouvre le document de réglages de l'utilisateur sur l'ordinateur du harness.","hset_general_document_opened":"Document de réglages ouvert sur l'hôte.","hset_general_document_unavailable":"Ce déploiement ne peut pas ouvrir le document de réglages.",
 "hset_models_empty":"Aucun fournisseur configurable dans cette version du harness.","hset_models_active":"Actif","hset_models_custom":"Personnalisé","hset_models_add_provider":"Ajouter un fournisseur","hset_models_add_custom":"Ajouter un fournisseur personnalisé","hset_models_edit":"Modifier","hset_models_remove":"Retirer","hset_models_remove_model":"Retirer le modèle","hset_models_remove_confirm_title":"Retirer %1$s ?","hset_models_remove_confirm":"Cela supprime la configuration du fournisseur des réglages du harness.","hset_models_key_label":"Clé API","hset_models_key_configured":"Configurée","hset_models_key_missing":"Non configurée","hset_models_key_hint":"Laissez vide pour conserver la clé stockée. La valeur n'est qu'écrite et jamais affichée à nouveau. Stockée sous %1$s.","hset_models_base_url":"URL de base","hset_models_api_protocol":"Protocole","hset_models_display_name":"Nom affiché","hset_models_custom_route":"Identifiant de route","hset_models_models_label":"Modèles","hset_models_models_hint_empty":"Pas de catalogue personnalisé : le catalogue intégré est utilisé.","hset_models_built_in_catalog":"Catalogue intégré","hset_models_count":"%1$d modèles","hset_models_add_model":"Ajouter un modèle","hset_models_model_id":"Identifiant du modèle","hset_models_model_name":"Nom","hset_models_model_context":"Fenêtre de contexte","hset_models_model_max_tokens":"Jeton max","hset_models_discover":"Découvrir les modèles","hset_models_discover_title":"Découvrir les modèles","hset_models_discover_hint":"Le harness demande à ce point d'entrée sa liste de modèles. Rien n'est envoyé au point d'entrée hormis l'URL de base et la clé de ce brouillon.","hset_models_discover_fetch":"Récupérer","hset_models_discover_apply":"Utiliser %1$d modèles sélectionnés","hset_models_discover_failed":"Échec de la découverte : %1$s","hset_models_discover_none":"Le point d'entrée n'a renvoyé aucun modèle.","hset_models_advanced":"Champs avancés (lecture seule)","hset_models_unknown_ns":"Ce fournisseur est configuré par une section que cette application ne modifie pas : %1$s",
 "hset_plugins_configurable":"Configurables","hset_plugins_inventory":"Inventaire","hset_plugins_card_shell":"Shell","hset_plugins_shell_timeout":"Délai de commande (ms)","hset_plugins_shell_max_output":"Sortie max (octets)","hset_plugins_card_agent_loop":"Boucle de l'agent","hset_plugins_agent_loop_max_parallel":"Appels d'outil parallèles max","hset_plugins_card_web_search":"Recherche web (DeepSeek)","hset_plugins_web_search_base_url":"URL de base","hset_plugins_web_search_max_uses":"Usages max","hset_plugins_base_value":"Par défaut : %1$s","hset_plugins_other":"Autres réglages (lecture seule)","hset_plugins_inventory_search":"Rechercher des extensions","hset_plugins_inventory_empty":"Aucune entrée d'extension.","hset_plugins_disabled":"Désactivé",
 "hset_presets_hint":"Les préréglages d'agent définissent avec quel modèle et quel prompt système démarrent les nouvelles sessions.","hset_preset_empty":"Aucun préréglage d'agent.","hset_preset_default":"Par défaut","hset_preset_trust_system":"Système","hset_preset_trust_user":"Utilisateur","hset_preset_broken":"Cassé : %1$s","hset_preset_view":"Voir le code source","hset_preset_set_default":"Définir par défaut","hset_preset_copy":"Copier…","hset_preset_copy_title":"Copier le préréglage","hset_preset_copy_hint":"Copie le contenu du préréglage source dans un nouveau préréglage utilisateur.","hset_preset_copy_id":"Nouvel identifiant de préréglage","hset_preset_copy_name":"Nom affiché (facultatif)","hset_preset_id_invalid":"Les identifiants de préréglage utilisent des minuscules, des chiffres et des tirets, et commencent par une lettre ou un chiffre.","hset_preset_delete_title":"Supprimer %1$s ?","hset_preset_delete_confirm":"Cela supprime le préréglage. Les sessions qui l'utilisent ne sont pas affectées.","hset_preset_default_saved":"Préréglage par défaut mis à jour.","hset_preset_copied":"Préréglage créé.","hset_preset_deleted":"Préréglage supprimé.",
 "hset_val_route_invalid":"Les identifiants de route utilisent des minuscules, des chiffres et des tirets, et commencent par une lettre.","hset_val_route_taken":"Cette route existe déjà.","hset_val_base_url_required":"L'URL de base est obligatoire.","hset_val_models_required":"Au moins un modèle est requis.","hset_val_model_prefix":"Modèle %1$d : %2$s","hset_val_model_id_required":"l'identifiant du modèle est obligatoire.","hset_val_model_id_duplicate":"identifiant de modèle en double.","hset_val_model_name":"le nom ne doit pas être vide.","hset_val_model_context":"la fenêtre de contexte doit être un entier positif.","hset_val_model_max_tokens":"le jeton max doit être un entier positif.","hset_val_api_key_blank":"Le champ de la clé ne contient que des espaces.","hset_val_api_key_format":"La clé semble enveloppée ou collée depuis une ligne d'environnement. Collez la clé brute.",
}

T["pt"] = {
 "hset_title":"Configurações do harness","hset_entry":"Configurações do harness","hset_tab_general":"Geral","hset_tab_models":"Modelos","hset_tab_plugins":"Extensões","hset_tab_presets":"Predefinições de agente",
 "hset_refused_banner":"Este harness não concedeu acesso remoto às configurações. Inicie-o com --allow-privileged-remote para editar as configurações deste dispositivo.","hset_unsupported_banner":"Esta compilação do harness não expõe o plano de configurações.","hset_readonly_banner":"A edição de configurações não está disponível; são exibidos valores somente de leitura.","hset_edit_available":"A edição de configurações está disponível neste harness.",
 "hset_load_error":"Não foi possível ler as configurações do harness: %1$s","hset_retry":"Tentar novamente","hset_saved":"Salvo.","hset_removed":"Removido.","hset_save_failed":"Falha ao salvar: %1$s","hset_conflict":"As configurações mudaram entretanto. Os valores mais recentes foram recarregados; tente novamente.","hset_not_connected":"Sem conexão com o harness.",
 "hset_general_preset_title":"Predefinição de agente","hset_general_preset_hint":"Aplica-se às sessões iniciadas a partir de agora.","hset_general_permission_title":"Permissões","hset_general_permission_hint":"Modo de permissão padrão para novas sessões.","hset_general_permission_no_session":"Nenhuma sessão aberta","hset_general_permission_unknown":"Desconhecido","hset_general_locale_title":"Idioma (interface web)","hset_general_locale_system":"Sistema","hset_general_locale_en":"Inglês","hset_general_locale_zh":"Chinês","hset_general_theme_title":"Aparência (interface web)","hset_general_theme_light":"Claro","hset_general_theme_dark":"Escuro","hset_general_theme_system":"Sistema","hset_general_open_document":"Abrir o documento de configurações","hset_general_open_document_hint":"Abre o documento de configurações do usuário no computador do harness.","hset_general_document_opened":"Documento de configurações aberto no host.","hset_general_document_unavailable":"Esta implantação não pode abrir o documento de configurações.",
 "hset_models_empty":"Não há provedores configuráveis nesta compilação do harness.","hset_models_active":"Ativo","hset_models_custom":"Personalizado","hset_models_add_provider":"Adicionar provedor","hset_models_add_custom":"Adicionar provedor personalizado","hset_models_edit":"Editar","hset_models_remove":"Remover","hset_models_remove_model":"Remover modelo","hset_models_remove_confirm_title":"Remover %1$s?","hset_models_remove_confirm":"Isso remove a configuração do provedor das configurações do harness.","hset_models_key_label":"Chave de API","hset_models_key_configured":"Configurada","hset_models_key_missing":"Não configurada","hset_models_key_hint":"Deixe em branco para manter a chave armazenada. O valor é apenas gravado e nunca mostrado de novo. Armazenada como %1$s.","hset_models_base_url":"URL base","hset_models_api_protocol":"Protocolo","hset_models_display_name":"Nome para exibição","hset_models_custom_route":"ID da rota","hset_models_models_label":"Modelos","hset_models_models_hint_empty":"Sem catálogo personalizado: o catálogo integrado é usado.","hset_models_built_in_catalog":"Catálogo integrado","hset_models_count":"%1$d modelos","hset_models_add_model":"Adicionar modelo","hset_models_model_id":"ID do modelo","hset_models_model_name":"Nome","hset_models_model_context":"Janela de contexto","hset_models_model_max_tokens":"Máx. de tokens","hset_models_discover":"Descobrir modelos","hset_models_discover_title":"Descobrir modelos","hset_models_discover_hint":"O harness consulta este ponto final pela sua lista de modelos. Nada é enviado ao ponto final além da URL base e da chave deste rascunho.","hset_models_discover_fetch":"Obter","hset_models_discover_apply":"Usar %1$d modelos selecionados","hset_models_discover_failed":"Falha na descoberta: %1$s","hset_models_discover_none":"O ponto final não retornou modelos.","hset_models_advanced":"Campos avançados (somente leitura)","hset_models_unknown_ns":"Este provedor é configurado por uma seção que este aplicativo não edita: %1$s",
 "hset_plugins_configurable":"Configuráveis","hset_plugins_inventory":"Inventário","hset_plugins_card_shell":"Shell","hset_plugins_shell_timeout":"Tempo limite do comando (ms)","hset_plugins_shell_max_output":"Saída máxima (bytes)","hset_plugins_card_agent_loop":"Laço do agente","hset_plugins_agent_loop_max_parallel":"Máx. de chamadas de ferramenta em paralelo","hset_plugins_card_web_search":"Pesquisa web (DeepSeek)","hset_plugins_web_search_base_url":"URL base","hset_plugins_web_search_max_uses":"Máx. de usos","hset_plugins_base_value":"Padrão: %1$s","hset_plugins_other":"Outras configurações (somente leitura)","hset_plugins_inventory_search":"Pesquisar extensões","hset_plugins_inventory_empty":"Não há entradas de extensão.","hset_plugins_disabled":"Desabilitado",
 "hset_presets_hint":"As predefinições de agente configuram com qual modelo e prompt de sistema as novas sessões começam.","hset_preset_empty":"Não há predefinições de agente.","hset_preset_default":"Padrão","hset_preset_trust_system":"Sistema","hset_preset_trust_user":"Usuário","hset_preset_broken":"Quebrado: %1$s","hset_preset_view":"Ver código-fonte","hset_preset_set_default":"Definir como padrão","hset_preset_copy":"Copiar…","hset_preset_copy_title":"Copiar predefinição","hset_preset_copy_hint":"Copia o conteúdo da predefinição de origem para uma nova predefinição de usuário.","hset_preset_copy_id":"Novo ID de predefinição","hset_preset_copy_name":"Nome para exibição (opcional)","hset_preset_id_invalid":"Os IDs de predefinição usam minúsculas, dígitos e hífens, e começam com uma letra ou dígito.","hset_preset_delete_title":"Excluir %1$s?","hset_preset_delete_confirm":"Isso remove a predefinição. As sessões que a usam não são afetadas.","hset_preset_default_saved":"Predefinição padrão atualizada.","hset_preset_copied":"Predefinição criada.","hset_preset_deleted":"Predefinição excluída.",
 "hset_val_route_invalid":"Os IDs de rota usam minúsculas, dígitos e hífens, e começam com uma letra.","hset_val_route_taken":"Essa rota já existe.","hset_val_base_url_required":"A URL base é obrigatória.","hset_val_models_required":"É necessário pelo menos um modelo.","hset_val_model_prefix":"Modelo %1$d: %2$s","hset_val_model_id_required":"o ID do modelo é obrigatório.","hset_val_model_id_duplicate":"ID de modelo duplicado.","hset_val_model_name":"o nome não pode estar em branco.","hset_val_model_context":"a janela de contexto deve ser um número inteiro positivo.","hset_val_model_max_tokens":"o máximo de tokens deve ser um número inteiro positivo.","hset_val_api_key_blank":"O campo da chave contém apenas espaços.","hset_val_api_key_format":"A chave parece envolta ou colada de uma linha de ambiente. Cole a chave bruta.",
}

T["ru"] = {
 "hset_title":"Настройки harness","hset_entry":"Настройки harness","hset_tab_general":"Общие","hset_tab_models":"Модели","hset_tab_plugins":"Плагины","hset_tab_presets":"Пресеты агента",
 "hset_refused_banner":"Этот harness не предоставил удалённый доступ к настройкам. Запустите его с --allow-privileged-remote, чтобы редактировать настройки с этого устройства.","hset_unsupported_banner":"Эта сборка harness не предоставляет плоскость настроек.","hset_readonly_banner":"Редактирование настроек недоступно; показаны значения только для чтения.","hset_edit_available":"Редактирование настроек доступно в этом harness.",
 "hset_load_error":"Не удалось прочитать настройки harness: %1$s","hset_retry":"Повторить","hset_saved":"Сохранено.","hset_removed":"Удалено.","hset_save_failed":"Не удалось сохранить: %1$s","hset_conflict":"Настройки изменились за это время. Загружены последние значения; повторите попытку.","hset_not_connected":"Нет подключения к harness.",
 "hset_general_preset_title":"Пресет агента","hset_general_preset_hint":"Применяется к сессиям, начинаемым отныне.","hset_general_permission_title":"Разрешения","hset_general_permission_hint":"Режим разрешений по умолчанию для новых сессий.","hset_general_permission_no_session":"Нет открытой сессии","hset_general_permission_unknown":"Неизвестно","hset_general_locale_title":"Язык (веб-интерфейс)","hset_general_locale_system":"Система","hset_general_locale_en":"Английский","hset_general_locale_zh":"Китайский","hset_general_theme_title":"Оформление (веб-интерфейс)","hset_general_theme_light":"Светлая","hset_general_theme_dark":"Тёмная","hset_general_theme_system":"Система","hset_general_open_document":"Открыть документ настроек","hset_general_open_document_hint":"Открывает пользовательский документ настроек на компьютере harness.","hset_general_document_opened":"Документ настроек открыт на хосте.","hset_general_document_unavailable":"Это развёртывание не может открыть документ настроек.",
 "hset_models_empty":"В этой сборке harness нет настраиваемых провайдеров.","hset_models_active":"Активен","hset_models_custom":"Пользовательский","hset_models_add_provider":"Добавить провайдера","hset_models_add_custom":"Добавить пользовательского провайдера","hset_models_edit":"Изменить","hset_models_remove":"Удалить","hset_models_remove_model":"Удалить модель","hset_models_remove_confirm_title":"Удалить %1$s?","hset_models_remove_confirm":"Это удаляет конфигурацию провайдера из настроек harness.","hset_models_key_label":"API-ключ","hset_models_key_configured":"Настроен","hset_models_key_missing":"Не настроен","hset_models_key_hint":"Оставьте пустым, чтобы сохранить текущий ключ. Значение только записывается и никогда не показывается снова. Хранится как %1$s.","hset_models_base_url":"Базовый URL","hset_models_api_protocol":"Протокол","hset_models_display_name":"Отображаемое имя","hset_models_custom_route":"ID маршрута","hset_models_models_label":"Модели","hset_models_models_hint_empty":"Нет пользовательского каталога: используется встроенный каталог.","hset_models_built_in_catalog":"Встроенный каталог","hset_models_count":"%1$d моделей","hset_models_add_model":"Добавить модель","hset_models_model_id":"ID модели","hset_models_model_name":"Имя","hset_models_model_context":"Контекстное окно","hset_models_model_max_tokens":"Макс. токенов","hset_models_discover":"Найти модели","hset_models_discover_title":"Найти модели","hset_models_discover_hint":"Harness запрашивает у этой конечной точки список моделей. На конечную точку ничего не отправляется, кроме базового URL и ключа этого черновика.","hset_models_discover_fetch":"Получить","hset_models_discover_apply":"Использовать %1$d выбранных моделей","hset_models_discover_failed":"Ошибка обнаружения: %1$s","hset_models_discover_none":"Конечная точка не вернула моделей.","hset_models_advanced":"Дополнительные поля (только чтение)","hset_models_unknown_ns":"Этот провайдер настраивается разделом, который это приложение не редактирует: %1$s",
 "hset_plugins_configurable":"Настраиваемые","hset_plugins_inventory":"Инвентарь","hset_plugins_card_shell":"Оболочка","hset_plugins_shell_timeout":"Таймаут команды (мс)","hset_plugins_shell_max_output":"Макс. выход (байт)","hset_plugins_card_agent_loop":"Цикл агента","hset_plugins_agent_loop_max_parallel":"Макс. параллельных вызовов инструментов","hset_plugins_card_web_search":"Веб-поиск (DeepSeek)","hset_plugins_web_search_base_url":"Базовый URL","hset_plugins_web_search_max_uses":"Макс. использований","hset_plugins_base_value":"По умолчанию: %1$s","hset_plugins_other":"Другие настройки (только чтение)","hset_plugins_inventory_search":"Поиск плагинов","hset_plugins_inventory_empty":"Нет записей плагинов.","hset_plugins_disabled":"Отключено",
 "hset_presets_hint":"Пресеты агента задают, с какой моделью и системным промптом начинаются новые сессии.","hset_preset_empty":"Нет пресетов агента.","hset_preset_default":"По умолчанию","hset_preset_trust_system":"Система","hset_preset_trust_user":"Пользователь","hset_preset_broken":"Сломан: %1$s","hset_preset_view":"Просмотреть исходник","hset_preset_set_default":"Сделать по умолчанию","hset_preset_copy":"Копировать…","hset_preset_copy_title":"Копировать пресет","hset_preset_copy_hint":"Копирует содержимое исходного пресета в новый пользовательский пресет.","hset_preset_copy_id":"Новый ID пресета","hset_preset_copy_name":"Отображаемое имя (необязательно)","hset_preset_id_invalid":"ID пресетов используют строчные буквы, цифры и дефисы и начинаются с буквы или цифры.","hset_preset_delete_title":"Удалить %1$s?","hset_preset_delete_confirm":"Это удалит пресет. Сессии, использующие его, не пострадают.","hset_preset_default_saved":"Пресет по умолчанию обновлён.","hset_preset_copied":"Пресет создан.","hset_preset_deleted":"Пресет удалён.",
 "hset_val_route_invalid":"ID маршрутов используют строчные буквы, цифры и дефисы и начинаются с буквы.","hset_val_route_taken":"Такой маршрут уже существует.","hset_val_base_url_required":"Базовый URL обязателен.","hset_val_models_required":"Требуется как минимум одна модель.","hset_val_model_prefix":"Модель %1$d: %2$s","hset_val_model_id_required":"ID модели обязателен.","hset_val_model_id_duplicate":"дублирующийся ID модели.","hset_val_model_name":"имя не может быть пустым.","hset_val_model_context":"контекстное окно должно быть положительным целым числом.","hset_val_model_max_tokens":"максимум токенов должен быть положительным целым числом.","hset_val_api_key_blank":"Поле ключа содержит только пробелы.","hset_val_api_key_format":"Ключ выглядит как обёрнутый или вставленный из строки окружения. Вставьте сырой ключ.",
}

T["ar"] = {
 "hset_title":"إعدادات harness","hset_entry":"إعدادات harness","hset_tab_general":"عام","hset_tab_models":"النماذج","hset_tab_plugins":"الإضافات","hset_tab_presets":"إعدادات مسبقة للوكيل",
 "hset_refused_banner":"لم يمنح هذا harness وصولاً عن بُعد إلى الإعدادات. شغّله مع --allow-privileged-remote لتحرير الإعدادات من هذا الجهاز.","hset_unsupported_banner":"هذا الإصدار من harness لا يعرض مستوى الإعدادات.","hset_readonly_banner":"تحرير الإعدادات غير متاح؛ تُعرض قيم للقراءة فقط.","hset_edit_available":"تحرير الإعدادات متاح في هذا harness.",
 "hset_load_error":"تعذّرت قراءة إعدادات harness: %1$s","hset_retry":"إعادة المحاولة","hset_saved":"تم الحفظ.","hset_removed":"تمت الإزالة.","hset_save_failed":"فشل الحفظ: %1$s","hset_conflict":"تغيّرت الإعدادات في الأثناء. أُعيد تحميل أحدث القيم؛ حاول مجدداً.","hset_not_connected":"غير متّصل بـ harness.",
 "hset_general_preset_title":"إعداد مسبق للوكيل","hset_general_preset_hint":"يُطبَّق على الجلسات التي تبدأ من الآن فصاعداً.","hset_general_permission_title":"الأذونات","hset_general_permission_hint":"وضع الأذونات الافتراضي للجلسات الجديدة.","hset_general_permission_no_session":"لا توجد جلسة مفتوحة","hset_general_permission_unknown":"غير معروف","hset_general_locale_title":"اللغة (واجهة الويب)","hset_general_locale_system":"النظام","hset_general_locale_en":"الإنجليزية","hset_general_locale_zh":"الصينية","hset_general_theme_title":"المظهر (واجهة الويب)","hset_general_theme_light":"فاتح","hset_general_theme_dark":"داكن","hset_general_theme_system":"النظام","hset_general_open_document":"فتح مستند الإعدادات","hset_general_open_document_hint":"يفتح مستند إعدادات المستخدم على حاسوب harness.","hset_general_document_opened":"فُتح مستند الإعدادات على المضيف.","hset_general_document_unavailable":"لا يمكن لهذا النشر فتح مستند الإعدادات.",
 "hset_models_empty":"لا يوجد مزوّدون قابلون للتكوين في هذا الإصدار من harness.","hset_models_active":"نشط","hset_models_custom":"مخصّص","hset_models_add_provider":"إضافة مزوّد","hset_models_add_custom":"إضافة مزوّد مخصّص","hset_models_edit":"تحرير","hset_models_remove":"إزالة","hset_models_remove_model":"إزالة النموذج","hset_models_remove_confirm_title":"إزالة %1$s؟","hset_models_remove_confirm":"تزيل هذا تكوين المزوّد من إعدادات harness.","hset_models_key_label":"مفتاح API","hset_models_key_configured":"مُكوَّن","hset_models_key_missing":"غير مُكوَّن","hset_models_key_hint":"اتركه فارغاً للإبقاء على المفتاح المحفوظ. يُكتب القيمة فقط ولا يُعرض مجدداً. يُحفظ باسم %1$s.","hset_models_base_url":"الرابط الأساسي","hset_models_api_protocol":"البروتوكول","hset_models_display_name":"الاسم المعروض","hset_models_custom_route":"معرّف المسار","hset_models_models_label":"النماذج","hset_models_models_hint_empty":"لا يوجد فهرس مخصّص: يُستخدم الفهرس المدمج.","hset_models_built_in_catalog":"الفهرس المدمج","hset_models_count":"%1$d نماذج","hset_models_add_model":"إضافة نموذج","hset_models_model_id":"معرّف النموذج","hset_models_model_name":"الاسم","hset_models_model_context":"نافذة السياق","hset_models_model_max_tokens":"الحد الأقصى للرموز","hset_models_discover":"اكتشاف النماذج","hset_models_discover_title":"اكتشاف النماذج","hset_models_discover_hint":"يسأل harness هذا الطرف عن قائمة نماذجه. لا يُرسَل إلى الطرف شيء سوى الرابط الأساسي والمفتاح في هذا المسودة.","hset_models_discover_fetch":"جلب","hset_models_discover_apply":"استخدام %1$d نماذج محددة","hset_models_discover_failed":"فشل الاكتشاف: %1$s","hset_models_discover_none":"لم يُرجِع الطرف أي نماذج.","hset_models_advanced":"حقول متقدمة (للقراءة فقط)","hset_models_unknown_ns":"يُكوَّن هذا المزوّد بواسطة قسم لا يحرّره هذا التطبيق: %1$s",
 "hset_plugins_configurable":"قابلة للتكوين","hset_plugins_inventory":"المخزون","hset_plugins_card_shell":"الصدفة","hset_plugins_shell_timeout":"مهلة الأمر (ملّي ثانية)","hset_plugins_shell_max_output":"الحد الأقصى للمخرجات (بايت)","hset_plugins_card_agent_loop":"حلقة الوكيل","hset_plugins_agent_loop_max_parallel":"الحد الأقصى لاستدعاءات الأدوات المتوازية","hset_plugins_card_web_search":"البحث في الويب (DeepSeek)","hset_plugins_web_search_base_url":"الرابط الأساسي","hset_plugins_web_search_max_uses":"الحد الأقصى للاستخدامات","hset_plugins_base_value":"الافتراضي: %1$s","hset_plugins_other":"إعدادات أخرى (للقراءة فقط)","hset_plugins_inventory_search":"البحث في الإضافات","hset_plugins_inventory_empty":"لا توجد إدخالات إضافات.","hset_plugins_disabled":"معطَّل",
 "hset_presets_hint":"تحدّد الإعدادات المسبقة للوكيل النموذج وموجّه النظام الذي تبدأ به الجلسات الجديدة.","hset_preset_empty":"لا توجد إعدادات مسبقة للوكيل.","hset_preset_default":"الافتراضي","hset_preset_trust_system":"النظام","hset_preset_trust_user":"المستخدم","hset_preset_broken":"معطوب: %1$s","hset_preset_view":"عرض المصدر","hset_preset_set_default":"تعيين كافتراضي","hset_preset_copy":"نسخ…","hset_preset_copy_title":"نسخ الإعداد المسبق","hset_preset_copy_hint":"ينسخ محتوى الإعداد المسبق المصدر إلى إعداد مسبق جديد للمستخدم.","hset_preset_copy_id":"معرّف جديد للإعداد المسبق","hset_preset_copy_name":"الاسم المعروض (اختياري)","hset_preset_id_invalid":"تستخدم معرّفات الإعدادات المسبقة أحرفاً صغيرة وأرقاماً وشرطات، وتبدأ بحرف أو رقم.","hset_preset_delete_title":"حذف %1$s؟","hset_preset_delete_confirm":"يحذف هذا الإعداد المسبق. لا تتأثر الجلسات التي تستخدمه.","hset_preset_default_saved":"تم تحديث الإعداد المسبق الافتراضي.","hset_preset_copied":"تم إنشاء الإعداد المسبق.","hset_preset_deleted":"تم حذف الإعداد المسبق.",
 "hset_val_route_invalid":"تستخدم معرّفات المسارات أحرفاً صغيرة وأرقاماً وشرطات، وتبدأ بحرف.","hset_val_route_taken":"هذا المسار موجود بالفعل.","hset_val_base_url_required":"الرابط الأساسي مطلوب.","hset_val_models_required":"مطلوب نموذج واحد على الأقل.","hset_val_model_prefix":"النموذج %1$d: %2$s","hset_val_model_id_required":"معرّف النموذج مطلوب.","hset_val_model_id_duplicate":"معرّف نموذج مكرر.","hset_val_model_name":"لا يمكن أن يكون الاسم فارغاً.","hset_val_model_context":"يجب أن تكون نافذة السياق عدداً صحيحاً موجباً.","hset_val_model_max_tokens":"يجب أن يكون الحد الأقصى للرموز عدداً صحيحاً موجباً.","hset_val_api_key_blank":"حقل المفتاح يحتوي على مسافات فقط.","hset_val_api_key_format":"يبدو المفتاح مغلّفاً أو م لصقاً من سطر متغيّر بيئي. الصق المفتاح الخام.",
}

T["bn"] = {
 "hset_title":"harness-এর সেটিংস","hset_entry":"harness-এর সেটিংস","hset_tab_general":"সাধারণ","hset_tab_models":"মডেল","hset_tab_plugins":"প্লাগ-ইন","hset_tab_presets":"এজেন্ট প্রিসেট",
 "hset_refused_banner":"এই harness-এর দূরবর্তী সেটিংস অ্যাক্সেস দেয়নি। এই ডিভাইস থেকে সেটিংস সম্পাদনা করতে --allow-privileged-remote দিয়ে চালু করুন।","hset_unsupported_banner":"এই harness বিল্ডটি সেটিংস প্লেন প্রদর্শন করে না।","hset_readonly_banner":"সেটিংস সম্পাদনা উপলব্ধ নয়; শুধুমাত্র পড়ার মূল্য দেখানো হচ্ছে।","hset_edit_available":"এই harness-এ সেটিংস সম্পাদনা উপলব্ধ।",
 "hset_load_error":"harness-এর সেটিংস পড়া যায়নি: %1$s","hset_retry":"আবার চেষ্টা করুন","hset_saved":"সংরক্ষিত।","hset_removed":"মুছে ফেলা হয়েছে।","hset_save_failed":"সংরক্ষণ ব্যর্থ: %1$s","hset_conflict":"এর মধ্যে সেটিংস পরিবর্তিত হয়েছে। সর্বশেষ মূল্য আবার লোড করা হয়েছে; আবার চেষ্টা করুন।","hset_not_connected":"harness-এ সংযুক্ত নয়।",
 "hset_general_preset_title":"এজেন্ট প্রিসেট","hset_general_preset_hint":"এই মুহূর্ত থেকে শুরু হওয়া সেশনে প্রযোজ্য।","hset_general_permission_title":"অনুমতি","hset_general_permission_hint":"নতুন সেশনের জন্য ডিফল্ট অনুমতি মোড।","hset_general_permission_no_session":"কোনো খোলা সেশন নেই","hset_general_permission_unknown":"অজানা","hset_general_locale_title":"ভাষা (ওয়েব GUI)","hset_general_locale_system":"সিস্টেম","hset_general_locale_en":"ইংরেজি","hset_general_locale_zh":"চীনা","hset_general_theme_title":"দৃষ্টি (ওয়েব GUI)","hset_general_theme_light":"লাইট","hset_general_theme_dark":"ডার্ক","hset_general_theme_system":"সিস্টেম","hset_general_open_document":"সেটিংস নথি খুলুন","hset_general_open_document_hint":"harness কম্পিউটারে ব্যবহারকারীর সেটিংস নথি খোলে।","hset_general_document_opened":"হোস্টে সেটিংস নথি খোলা হয়েছে।","hset_general_document_unavailable":"এই ডিপ্লয়মেন্ট সেটিংস নথি খুলতে পারে না।",
 "hset_models_empty":"এই harness বিল্ডে কোনো কনফিগারেবল প্রোভাইডার নেই।","hset_models_active":"সক্রিয়","hset_models_custom":"কাস্টম","hset_models_add_provider":"প্রোভাইডার যোগ করুন","hset_models_add_custom":"কাস্টম প্রোভাইডার যোগ করুন","hset_models_edit":"সম্পাদনা","hset_models_remove":"মুছুন","hset_models_remove_model":"মডেল মুছুন","hset_models_remove_confirm_title":"%1$s মুছবেন?","hset_models_remove_confirm":"এটি harness-এর সেটিংস থেকে প্রোভাইডারের কনফিগারেশন মুছে ফেলে।","hset_models_key_label":"API কী","hset_models_key_configured":"সংরচিত","hset_models_key_missing":"সংরচিত নয়","hset_models_key_hint":"সংরক্ষিত কী রাখতে খালি রাখুন। মান শুধু লেখা হয় এবং আবার দেখানো হয় না। %1$s হিসেবে সংরক্ষিত।","hset_models_base_url":"বেস URL","hset_models_api_protocol":"প্রোটোকল","hset_models_display_name":"প্রদর্শিত নাম","hset_models_custom_route":"রুট ID","hset_models_models_label":"মডেল","hset_models_models_hint_empty":"কোনো কাস্টম ক্যাটালগ নেই: বিল্ট-ইন ক্যাটালগ ব্যবহৃত হয়।","hset_models_built_in_catalog":"বিল্ট-ইন ক্যাটালগ","hset_models_count":"%1$dটি মডেল","hset_models_add_model":"মডেল যোগ করুন","hset_models_model_id":"মডেল ID","hset_models_model_name":"নাম","hset_models_model_context":"কনটেক্সট উইন্ডো","hset_models_model_max_tokens":"সর্বোচ্ টোকেন","hset_models_discover":"মডেল আবিষ্কার","hset_models_discover_title":"মডেল আবিষ্কার","hset_models_discover_hint":"harness এই এন্ডপয়েন্ট থেকে তার মডেল তালিকা চায়। এই খসড়াটির বেস URL এবং কী ছাড়া এন্ডপয়েন্টে কিছু পাঠানো হয় না।","hset_models_discover_fetch":"আনুন","hset_models_discover_apply":"%1$dটি নির্বাচিত মডেল ব্যবহার করুন","hset_models_discover_failed":"আবিষ্কার ব্যর্থ: %1$s","hset_models_discover_none":"এন্ডপয়েন্ট কোনো মডেল ফেরত দেয়নি।","hset_models_advanced":"উন্নত ফিল্ড (শুধু পড়া)","hset_models_unknown_ns":"এই প্রোভাইডারটি একটি সেকশন দ্বারা কনফিগার করা, যা এই অ্যাপ সম্পাদনা করে না: %1$s",
 "hset_plugins_configurable":"কনফিগারেবল","hset_plugins_inventory":"ইনভেন্টরি","hset_plugins_card_shell":"শেল","hset_plugins_shell_timeout":"কমান্ড টাইমআউট (ms)","hset_plugins_shell_max_output":"সর্বোচ্ আউটপুট (বাইট)","hset_plugins_card_agent_loop":"এজেন্ট লুপ","hset_plugins_agent_loop_max_parallel":"সর্বোচ্ সমান্তরাল টুল কল","hset_plugins_card_web_search":"ওয়েব সার্চ (DeepSeek)","hset_plugins_web_search_base_url":"বেস URL","hset_plugins_web_search_max_uses":"সর্বোচ্ ব্যবহার","hset_plugins_base_value":"ডিফল্ট: %1$s","hset_plugins_other":"অন্যান্য সেটিংস (শুধু পড়া)","hset_plugins_inventory_search":"প্লাগ-ইন খুঁজুন","hset_plugins_inventory_empty":"কোনো প্লাগ-ইন এন্ট্রি নেই।","hset_plugins_disabled":"বিরক্তিকর",
 "hset_presets_hint":"এজেন্ট প্রিসেট নির্ধারণ করে কোন মডেল এবং সিস্টেম প্রম্পট দিয়ে নতুন সেশন শুরু হয়।","hset_preset_empty":"কোনো এজেন্ট প্রিসেট নেই।","hset_preset_default":"ডিফল্ট","hset_preset_trust_system":"সিস্টেম","hset_preset_trust_user":"ব্যবহারকারী","hset_preset_broken":"ভাঙা: %1$s","hset_preset_view":"সোর্স দেখুন","hset_preset_set_default":"ডিফল্ট হিসেবে সেট করুন","hset_preset_copy":"কপি…","hset_preset_copy_title":"প্রিসেট কপি করুন","hset_preset_copy_hint":"সোর্স প্রিসেটের কনটেন্ট একটি নতুন ব্যবহারকারীর প্রিসেটে কপি করে।","hset_preset_copy_id":"নতুন প্রিসেট ID","hset_preset_copy_name":"প্রদর্শিত নাম (ঐচ্ছিক)","hset_preset_id_invalid":"প্রিসেট ID ছোট হাত, সংখ্যা এবং হাইফেন ব্যবহার করে, এবং একটি অক্ষর বা সংখ্যা দিয়ে শুরু হয়।","hset_preset_delete_title":"%1$s মুছবেন?","hset_preset_delete_confirm":"এটি প্রিসেটটি মুছে ফেলে। এটি ব্যবহারকারী সেশন প্রভাবিত হয় না।","hset_preset_default_saved":"ডিফল্ট প্রিসেট হালনাগাদ করা হয়েছে।","hset_preset_copied":"প্রিসেট তৈরি করা হয়েছে।","hset_preset_deleted":"প্রিসেট মুছে ফেলা হয়েছে।",
 "hset_val_route_invalid":"রুট ID ছোট হাত, সংখ্যা এবং হাইফেন ব্যবহার করে, এবং একটি অক্ষর দিয়ে শুরু হয়।","hset_val_route_taken":"এই রুটটি ইতিমধ্যে বিদ্যমান।","hset_val_base_url_required":"বেস URL আবশ্যক।","hset_val_models_required":"কমপক্ষে একটি মডেল আবশ্যক।","hset_val_model_prefix":"মডেল %1$d: %2$s","hset_val_model_id_required":"মডেল ID আবশ্যক।","hset_val_model_id_duplicate":"দ্বিতীয় মডেল ID।","hset_val_model_name":"নাম খালি হতে পারে না।","hset_val_model_context":"কনটেক্সট উইন্ডো একটি ধনাত্মক পূর্ণসংখ্যা হতে হবে।","hset_val_model_max_tokens":"সর্বোচ্ টোকেন একটি ধনাত্মক পূর্ণসংখ্যা হতে হবে।","hset_val_api_key_blank":"কী ফিল্ডটি শুধু স্পেস ধারণ করে।","hset_val_api_key_format":"কীটি মোড়ানো বা একটি পরিবেশ লাইন থেকে পেস্ট করা মনে হচ্ছে। কাঁচা কীটি পেস্ট করুন।",
}

T["hi"] = {
 "hset_title":"harness की सेटिंग्स","hset_entry":"harness की सेटिंग्स","hset_tab_general":"सामान्य","hset_tab_models":"मॉडल","hset_tab_plugins":"प्लग-इन","hset_tab_presets":"एजेंट प्रीसेट",
 "hset_refused_banner":"इस harness ने दूरवर्ती सेटिंग्स एक्सेस नहीं दिया। इस डिवाइस से सेटिंग्स संपादित करने के लिए --allow-privileged-remote के साथ चलाएँ।","hset_unsupported_banner":"यह harness बिल्ड सेटिंग्स प्लेन प्रदर्शित नहीं करता।","hset_readonly_banner":"सेटिंग्स संपादन उपलब्ध नहीं है; केवल-पढ़ने के मान दिखाए जा रहे हैं।","hset_edit_available":"इस harness पर सेटिंग्स संपादन उपलब्ध है।",
 "hset_load_error":"harness की सेटिंग्स पढ़ी नहीं जा सकीं: %1$s","hset_retry":"फिर से कोशिश करें","hset_saved":"सहेजा गया।","hset_removed":"हटाया गया।","hset_save_failed":"सहेजना विफल: %1$s","hset_conflict":"इस बीच सेटिंग्स बदल गईं। नवीनतम मान फिर से लोड किए गए; फिर से कोशिश करें।","hset_not_connected":"harness से जुड़ा नहीं है।",
 "hset_general_preset_title":"एजेंट प्रीसेट","hset_general_preset_hint":"अब से शुरू होने वाली सत्रों पर लागू होता है।","hset_general_permission_title":"अनुमति","hset_general_permission_hint":"नए सत्रों के लिए डिफ़ॉल्ट अनुमति मोड।","hset_general_permission_no_session":"कोई खुला सत्र नहीं","hset_general_permission_unknown":"अज्ञात","hset_general_locale_title":"भाषा (वेब GUI)","hset_general_locale_system":"सिस्टम","hset_general_locale_en":"अंग्रेज़ी","hset_general_locale_zh":"चीनी","hset_general_theme_title":"रूप (वेब GUI)","hset_general_theme_light":"लाइट","hset_general_theme_dark":"डार्क","hset_general_theme_system":"सिस्टम","hset_general_open_document":"सेटिंग्स दस्तावेज़ खोलें","hset_general_open_document_hint":"harness कंप्यूटर पर उपयोगकर्ता सेटिंग्स दस्तावेज़ खोलता है।","hset_general_document_opened":"होस्ट पर सेटिंग्स दस्तावेज़ खुला गया।","hset_general_document_unavailable":"यह डेप्लॉयमेंट सेटिंग्स दस्तावेज़ नहीं खोल सकता।",
 "hset_models_empty":"इस harness बिल्ड में कोई कॉन्फ़िगरेबल प्रोवाइडर नहीं है।","hset_models_active":"सक्रिय","hset_models_custom":"कस्टम","hset_models_add_provider":"प्रोवाइडर जोड़ें","hset_models_add_custom":"कस्टम प्रोवाइडर जोड़ें","hset_models_edit":"संपादित करें","hset_models_remove":"हटाएँ","hset_models_remove_model":"मॉडल हटाएँ","hset_models_remove_confirm_title":"%1$s हटाएँ?","hset_models_remove_confirm":"यह harness की सेटिंग्स से प्रोवाइडर की कॉन्फ़िगरेशन हटा देता है।","hset_models_key_label":"API कुंजी","hset_models_key_configured":"कॉन्फ़िगर्ड","hset_models_key_missing":"कॉन्फ़िगर्ड नहीं","hset_models_key_hint":"सहेजी गई कुंजी रखने के लिए खाली छोड़ें। मान केवल लिखा जाता है और फिर कभी नहीं दिखाया जाता है। %1$s के रूप में संग्रहीत।","hset_models_base_url":"बेस URL","hset_models_api_protocol":"प्रोटोकॉल","hset_models_display_name":"प्रदर्शित नाम","hset_models_custom_route":"रूट ID","hset_models_models_label":"मॉडल","hset_models_models_hint_empty":"कोई कस्टम कैटलॉग नहीं: बिल्ट-इन कैटलॉग का उपयोग होता है।","hset_models_built_in_catalog":"बिल्ट-इन कैटलॉग","hset_models_count":"%1$d मॉडल","hset_models_add_model":"मॉडल जोड़ें","hset_models_model_id":"मॉडल ID","hset_models_model_name":"नाम","hset_models_model_context":"कॉन्टेक्स्ट विंडो","hset_models_model_max_tokens":"अधिकतम टोकन","hset_models_discover":"मॉडल खोजें","hset_models_discover_title":"मॉडल खोजें","hset_models_discover_hint":"harness इस एंडपॉइंट से उसकी मॉडल सूची माँगता है। इस ड्राफ्ट के बेस URL और कुंजी के अलावा एंडपॉइंट पर कुछ भेजा नहीं जाता।","hset_models_discover_fetch":"प्राप्त करें","hset_models_discover_apply":"%1$d चयनित मॉडल उपयोग करें","hset_models_discover_failed":"खोज विफल: %1$s","hset_models_discover_none":"एंडपॉइंट ने कोई मॉडल लौटाया नहीं।","hset_models_advanced":"उन्नत फ़ील्ड (केवल पढ़ने के लिए)","hset_models_unknown_ns":"यह प्रोवाइडर एक सेक्शन द्वारा कॉन्फ़िगर किया गया है, जिसे यह ऐप संपादित नहीं करता: %1$s",
 "hset_plugins_configurable":"कॉन्फ़िगरेबल","hset_plugins_inventory":"इन्वेंटरी","hset_plugins_card_shell":"शेल","hset_plugins_shell_timeout":"कमांड टाइमआउट (ms)","hset_plugins_shell_max_output":"अधिकतम आउटपुट (बाइट)","hset_plugins_card_agent_loop":"एजेंट लूप","hset_plugins_agent_loop_max_parallel":"अधिकतम समानांतर टूल कॉल","hset_plugins_card_web_search":"वेब सर्च (DeepSeek)","hset_plugins_web_search_base_url":"बेस URL","hset_plugins_web_search_max_uses":"अधिकतम उपयोग","hset_plugins_base_value":"डिफ़ॉल्ट: %1$s","hset_plugins_other":"अन्य सेटिंग्स (केवल पढ़ने के लिए)","hset_plugins_inventory_search":"प्लग-इन खोजें","hset_plugins_inventory_empty":"कोई प्लग-इन प्रविष्टि नहीं।","hset_plugins_disabled":"निष्क्रिय",
 "hset_presets_hint":"एजेंट प्रीसेट निर्धारित करते हैं कि नए सत्र किस मॉडल और सिस्टम प्रॉम्प्ट से शुरू होते हैं।","hset_preset_empty":"कोई एजेंट प्रीसेट नहीं।","hset_preset_default":"डिफ़ॉल्ट","hset_preset_trust_system":"सिस्टम","hset_preset_trust_user":"उपयोगकर्ता","hset_preset_broken":"टूटा: %1$s","hset_preset_view":"सोर्स देखें","hset_preset_set_default":"डिफ़ॉल्ट के रूप में सेट करें","hset_preset_copy":"कॉपी…","hset_preset_copy_title":"प्रीसेट कॉपी करें","hset_preset_copy_hint":"सोर्स प्रीसेट की सामग्री एक नए उपयोगकर्ता प्रीसेट में कॉपी करता है।","hset_preset_copy_id":"नया प्रीसेट ID","hset_preset_copy_name":"प्रदर्शित नाम (वैकल्पिक)","hset_preset_id_invalid":"प्रीसेट ID छोटे अक्षर, अंक और हाइफन उपयोग करते हैं, और एक अक्षर या अंक से शुरू होते हैं।","hset_preset_delete_title":"%1$s हटाएँ?","hset_preset_delete_confirm":"यह प्रीसेट हटा देता है। उसे उपयोग करने वाले सत्र प्रभावित नहीं होते।","hset_preset_default_saved":"डिफ़ॉल्ट प्रीसेट अद्यतन किया गया।","hset_preset_copied":"प्रीसेट बनाया गया।","hset_preset_deleted":"प्रीसेट हटा दिया गया।",
 "hset_val_route_invalid":"रूट ID छोटे अक्षर, अंक और हाइफन उपयोग करते हैं, और एक अक्षर से शुरू होते हैं।","hset_val_route_taken":"वह रूट पहले से मौजूद है।","hset_val_base_url_required":"बेस URL आवश्यक है।","hset_val_models_required":"कम से कम एक मॉडल आवश्यक है।","hset_val_model_prefix":"मॉडल %1$d: %2$s","hset_val_model_id_required":"मॉडल ID आवश्यक है।","hset_val_model_id_duplicate":"दोहरा मॉडल ID।","hset_val_model_name":"नाम खाली नहीं हो सकता।","hset_val_model_context":"कॉन्टेक्स्ट विंडो एक धनात्मक पूर्णांक होना चाहिए।","hset_val_model_max_tokens":"अधिकतम टोकन एक धनात्मक पूर्णांक होना चाहिए।","hset_val_api_key_blank":"कुंजी फ़ील्ड में केवल स्थान हैं।","hset_val_api_key_format":"कुंजी लिपटी हुई या एक पर्यावरण पंक्ति से चिपकाई गई लगती है। कच्ची कुंजी चिपकाएँ।",
}

T["th"] = {
 "hset_title":"การตั้งค่า harness","hset_entry":"การตั้งค่า harness","hset_tab_general":"ทั่วไป","hset_tab_models":"โมเดล","hset_tab_plugins":"ปลั๊กอิน","hset_tab_presets":"โปรไฟล์เอเจนต์",
 "hset_refused_banner":"harness นี้ไม่ได้ให้สิทธิ์เข้าถึงการตั้งค่าระยะไกล เริ่มใช้งานด้วย --allow-privileged-remote เพื่อแก้ไขการตั้งค่าจากอุปกรณ์นี้","hset_unsupported_banner":"การ build นี้ของ harness ไม่ได้เปิดระนาบการตั้งค่า","hset_readonly_banner":"การแก้ไขการตั้งค่าไม่พร้อมใช้งาน แสดงเฉพาะค่าที่อ่านได้","hset_edit_available":"การแก้ไขการตั้งค่าพร้อมใช้งานใน harness นี้",
 "hset_load_error":"ไม่สามารถอ่านการตั้งค่าของ harness: %1$s","hset_retry":"ลองใหม่","hset_saved":"บันทึกแล้ว","hset_removed":"ลบแล้ว","hset_save_failed":"บันทึกไม่สำเร็จ: %1$s","hset_conflict":"การตั้งค่าเปลี่ยนไปในช่วงนั้น ค่าล่าสุดถูกรีดโหลดแล้ว ลองใหม่","hset_not_connected":"ไม่เชื่อมต่อกับ harness",
 "hset_general_preset_title":"โปรไฟล์เอเจนต์","hset_general_preset_hint":"ใช้กับเซสชันที่เริ่มจากตอนนี้เป็นต้นไป","hset_general_permission_title":"สิทธิ์","hset_general_permission_hint":"โหมดสิทธิ์เริ่มต้นสำหรับเซสชันใหม่","hset_general_permission_no_session":"ไม่มีเซสชันที่เปิดอยู่","hset_general_permission_unknown":"ไม่ทราบ","hset_general_locale_title":"ภาษา (GUI เว็บ)","hset_general_locale_system":"ระบบ","hset_general_locale_en":"อังกฤษ","hset_general_locale_zh":"จีน","hset_general_theme_title":"การแสดงผล (GUI เว็บ)","hset_general_theme_light":"สว่าง","hset_general_theme_dark":"มืด","hset_general_theme_system":"ระบบ","hset_general_open_document":"เปิดเอกสารการตั้งค่า","hset_general_open_document_hint":"เปิดเอกสารการตั้งค่าของผู้ใช้บนคอมพิวเตอร์ของ harness","hset_general_document_opened":"เปิดเอกสารการตั้งค่าบนโฮสต์แล้ว","hset_general_document_unavailable":"การ deploy นี้ไม่สามารถเปิดเอกสารการตั้งค่าได้",
 "hset_models_empty":"ไม่มีผู้ให้บริการที่ปรับค่าได้ใน harness build นี้","hset_models_active":"ใช้งาน","hset_models_custom":"กำหนดเอง","hset_models_add_provider":"เพิ่มผู้ให้บริการ","hset_models_add_custom":"เพิ่มผู้ให้บริการกำหนดเอง","hset_models_edit":"แก้ไข","hset_models_remove":"ลบ","hset_models_remove_model":"ลบโมเดล","hset_models_remove_confirm_title":"ลบ %1$s?","hset_models_remove_confirm":"น้ีจะลบการตั้งค่าของผู้ให้บริการจากการตั้งค่าของ harness","hset_models_key_label":"คีย์ API","hset_models_key_configured":"ตั้งค่าแล้ว","hset_models_key_missing":"ยังไม่ได้ตั้งค่า","hset_models_key_hint":"เว้นว่างเพื่อรักษาคีย์ที่เก็บไว้ ค่าจะถูกเขียนเท่านั้นและจะไม่แสดงอีก เก็บเป็น %1$s","hset_models_base_url":"URL พื้นฐาน","hset_models_api_protocol":"โปรโตคอล","hset_models_display_name":"ชื่อที่แสดง","hset_models_custom_route":"ID เส้นทาง","hset_models_models_label":"โมเดล","hset_models_models_hint_empty":"ไม่มีแคตตาล็อกกำหนดเอง: ใช้แคตตาล็อกในตัว","hset_models_built_in_catalog":"แคตตาล็อกในตัว","hset_models_count":"%1$d โมเดล","hset_models_add_model":"เพิ่มโมเดล","hset_models_model_id":"ID โมเดล","hset_models_model_name":"ชื่อ","hset_models_model_context":"หน้าต่างบริบท","hset_models_model_max_tokens":"โทเคนสูงสุด","hset_models_discover":"ค้นหโมเดล","hset_models_discover_title":"ค้นหโมเดล","hset_models_discover_hint":"harness ถามรายการโมเดลจาก endpoint นี้ ไม่มีการส่งอะไรไปยัง endpoint นอกจาก URL พื้นฐานและคีย์ของร่างนี้","hset_models_discover_fetch":"ดึง","hset_models_discover_apply":"ใช้โมเดลที่เลือก %1$d","hset_models_discover_failed":"การค้นหาล้มเหลว: %1$s","hset_models_discover_none":"endpoint ไม่ได้คืนโมเดล","hset_models_advanced":"ฟิลด์ขั้นสูง (อ่านได้เท่านั้น)","hset_models_unknown_ns":"ผู้ให้บริการนี้ถูกตั้งค่าโดยส่วนที่แอปนี้ไม่แก้ไข: %1$s",
 "hset_plugins_configurable":"ปรับค่าได้","hset_plugins_inventory":"สินค้าคงคลัง","hset_plugins_card_shell":"Shell","hset_plugins_shell_timeout":"เวลาหมดเขตของคำสั่ง (ms)","hset_plugins_shell_max_output":"เอาต์พุตสูงสุด (ไบต์)","hset_plugins_card_agent_loop":"ลูปของเอเจนต์","hset_plugins_agent_loop_max_parallel":"การเรียกเครื่องมือแบบขนานสูงสุด","hset_plugins_card_web_search":"ค้นหาเว็บ (DeepSeek)","hset_plugins_web_search_base_url":"URL พื้นฐาน","hset_plugins_web_search_max_uses":"การใช้งานสูงสุด","hset_plugins_base_value":"เริ่มต้น: %1$s","hset_plugins_other":"การตั้งค่าอื่น (อ่านได้เท่านั้น)","hset_plugins_inventory_search":"ค้นหาปลั๊กอิน","hset_plugins_inventory_empty":"ไม่มีรายการปลั๊กอิน","hset_plugins_disabled":"ปิดใช้งาน",
 "hset_presets_hint":"โปรไฟล์เอเจนต์กำหนดว่าโมเดลและ system prompt ใดที่เซสชันใหม่จะเริ่ม","hset_preset_empty":"ไม่มีโปรไฟล์เอเจนต์","hset_preset_default":"เริ่มต้น","hset_preset_trust_system":"ระบบ","hset_preset_trust_user":"ผู้ใช้","hset_preset_broken":"เสียหาย: %1$s","hset_preset_view":"ดูซอร์ส","hset_preset_set_default":"ตั้งเป็นเริ่มต้น","hset_preset_copy":"คัดลอก…","hset_preset_copy_title":"คัดลอกโปรไฟล์","hset_preset_copy_hint":"คัดลอกเนื้อหาของโปรไฟล์ต้นฉบับไปยังโปรไฟล์ผู้ใช้ใหม่","hset_preset_copy_id":"ID โปรไฟล์ใหม่","hset_preset_copy_name":"ชื่อที่แสดง (ไม่บังคับ)","hset_preset_id_invalid":"ID โปรไฟล์ใช้ตัวพิมพ์เล็ก ตัวเลข และขีดกลาง และเริ่มด้วยตัวอักษรหรือตัวเลข","hset_preset_delete_title":"ลบ %1$s?","hset_preset_delete_confirm":"น้ีจะลบโปรไฟล์ เซสชันที่ใช้มันจะไม่ได้รับผลกระทบ","hset_preset_default_saved":"อัปเดตโปรไฟล์เริ่มต้นแล้ว","hset_preset_copied":"สร้างโปรไฟล์แล้ว","hset_preset_deleted":"ลบโปรไฟล์แล้ว",
 "hset_val_route_invalid":"ID เส้นทางใช้ตัวพิมพ์เล็ก ตัวเลข และขีดกลาง และเริ่มด้วยตัวอักษร","hset_val_route_taken":"เส้นทางนี้มีอยู่แล้ว","hset_val_base_url_required":"URL พื้นฐานเป็นสิ่งที่จำเป็น","hset_val_models_required":"ต้องมีโมเดลอย่างน้อยหนึ่งตัว","hset_val_model_prefix":"โมเดล %1$d: %2$s","hset_val_model_id_required":"ID โมเดลเป็นสิ่งที่จำเป็น","hset_val_model_id_duplicate":"ID โมเดลซ้ำ","hset_val_model_name":"ชื่อต้องไม่ว่าง","hset_val_model_context":"หน้าต่างบริบทต้องเป็นจำนวนเต็มบวก","hset_val_model_max_tokens":"โทเคนสูงสุดต้องเป็นจำนวนเต็มบวก","hset_val_api_key_blank":"ช่องคีย์มีเฉพาะช่องว่าง","hset_val_api_key_format":"คีย์ดูเหมือนถูกห่อหรือวางจากบรรทัดของ environment วางคีย์ดิบ",
}

T["ur"] = {
 "hset_title":"harness کی ترتیبات","hset_entry":"harness کی ترتیبات","hset_tab_general":"عمومی","hset_tab_models":"ماڈل","hset_tab_plugins":"پلگ ان","hset_tab_presets":"ایجنٹ پری سیٹ",
 "hset_refused_banner":"اس harness نے دور ترتیبات تک رسائی نہیں دی۔ اس آلے سے ترتیبات میں ترمیم کرنے کے لیے --allow-privileged-remote کے ساتھ شروع کریں۔","hset_unsupported_banner":"اس harness بلڈ ترتیبات کا پلین ظاہر نہیں کرتا۔","hset_readonly_banner":"ترتیبات کی ترمیم دستیاب نہیں ہے؛ صرف پڑھنے کے لیے اقدار دکھائی جا رہی ہیں۔","hset_edit_available":"اس harness پر ترتیبات کی ترمیم دستیاب ہے۔",
 "hset_load_error":"harness کی ترتیبات پڑھ نہیں سکی گئیں: %1$s","hset_retry":"دوبارہ کوشش کریں","hset_saved":"محفوظ کیا گیا۔","hset_removed":"ہٹا دیا گیا۔","hset_save_failed":"محفوظ کرنا ناکام: %1$s","hset_conflict":"اس دوران ترتیبات بدل گئیں۔ تازہ ترین اقدار دوبارہ لوڈ ہوئیں؛ دوبارہ کوشش کریں۔","hset_not_connected":"harness سے منسلک نہیں۔",
 "hset_general_preset_title":"ایجنٹ پری سیٹ","hset_general_preset_hint":"اب سے شروع ہونے والی نشستوں پر لاگو ہوتا ہے۔","hset_general_permission_title":"اجازت","hset_general_permission_hint":"نئی نشستوں کے لیے ڈیفالٹ اجازت موڈ۔","hset_general_permission_no_session":"کوئی کھلی نشست نہیں","hset_general_permission_unknown":"نامعلوم","hset_general_locale_title":"زبان (ویب GUI)","hset_general_locale_system":"سسٹم","hset_general_locale_en":"انگریزی","hset_general_locale_zh":"چینی","hset_general_theme_title":"دکھ (ویب GUI)","hset_general_theme_light":"لائٹ","hset_general_theme_dark":"ڈارک","hset_general_theme_system":"سسٹم","hset_general_open_document":"ترتیبات کا دستاویز کھولیں","hset_general_open_document_hint":"harness کمپیوٹر پر صارف کے ترتیبات کے دستاویز کو کھولتا ہے۔","hset_general_document_opened":"ہوسٹ پر ترتیبات کا دستاویز کھول دیا گیا۔","hset_general_document_unavailable":"یہ ڈیپلوائمنٹ ترتیبات کا دستاویز نہیں کھول سکتا۔",
 "hset_models_empty":"اس harness بلڈ میں کوئی قابلِ ترتیب فراہم کنندہ نہیں ہے۔","hset_models_active":"فعال","hset_models_custom":"کسٹم","hset_models_add_provider":"فراہم کنندہ شامل کریں","hset_models_add_custom":"کسٹم فراہم کنندہ شامل کریں","hset_models_edit":"ترمیم","hset_models_remove":"ہٹائیں","hset_models_remove_model":"ماڈل ہٹائیں","hset_models_remove_confirm_title":"%1$s ہٹائیں؟","hset_models_remove_confirm":"یہ فراہم کنندہ کی ترتیب کو harness کی ترتیبات سے ہٹا دیتا ہے۔","hset_models_key_label":"API کلید","hset_models_key_configured":"ترتیب دی گئی","hset_models_key_missing":"ترتیب نہیں دی گئی","hset_models_key_hint":"محفوظ کلید برقرار رکھنے کے لیے خالی چھوڑیں۔ قدر صرف لکھی جاتی ہے اور دوبارہ دکھائی نہیں جاتی۔ %1$s کے طور پر محفوظ۔","hset_models_base_url":"بنیادی URL","hset_models_api_protocol":"پروٹوکول","hset_models_display_name":"دکھائی جانے والا نام","hset_models_custom_route":"راؤٹ ID","hset_models_models_label":"ماڈل","hset_models_models_hint_empty":"کوئی کسٹم کیٹلاگ نہیں: بلٹ ان کیٹلاگ استعمال ہوتا ہے۔","hset_models_built_in_catalog":"بلٹ ان کیٹلاگ","hset_models_count":"%1$d ماڈل","hset_models_add_model":"ماڈل شامل کریں","hset_models_model_id":"ماڈل ID","hset_models_model_name":"نام","hset_models_model_context":"کنٹیکسٹ ونڈو","hset_models_model_max_tokens":"زیادہ سے زیادہ ٹوکن","hset_models_discover":"ماڈل دریافت کریں","hset_models_discover_title":"ماڈل دریافت کریں","hset_models_discover_hint":"harness اس اینڈ پوائنٹ سے اپنے ماڈل کی فہرست مانگتا ہے۔ اس ڈرافٹ کے بنیادی URL اور کلید کے علاوہ اینڈ پوائنٹ کو کچھ بھی نہیں بھیجا جاتا۔","hset_models_discover_fetch":"لائیں","hset_models_discover_apply":"منتخب %1$d ماڈل استعمال کریں","hset_models_discover_failed":"دریافت ناکام: %1$s","hset_models_discover_none":"اینڈ پوائنٹ نے کوئی ماڈل واپس نہیں کیا۔","hset_models_advanced":"اعلیٰ فیلڈز (صرف پڑھنے کے لیے)","hset_models_unknown_ns":"یہ فراہم کنندہ ایک سیکشن سے ترتیب دیا گیا ہے جسے یہ ایپ ترمیم نہیں کرتا: %1$s",
 "hset_plugins_configurable":"قابلِ ترتیب","hset_plugins_inventory":"انوینٹری","hset_plugins_card_shell":"شل","hset_plugins_shell_timeout":"کمانڈ ٹائم آؤٹ (ms)","hset_plugins_shell_max_output":"زیادہ سے زیادہ آؤٹ پٹ (بائٹ)","hset_plugins_card_agent_loop":"ایجنٹ لوپ","hset_plugins_agent_loop_max_parallel":"زیادہ سے زیادہ متوازی ٹول کال","hset_plugins_card_web_search":"ویب سرچ (DeepSeek)","hset_plugins_web_search_base_url":"بنیادی URL","hset_plugins_web_search_max_uses":"زیادہ سے زیادہ استعمال","hset_plugins_base_value":"ڈیفالٹ: %1$s","hset_plugins_other":"دیگر ترتیبات (صرف پڑھنے کے لیے)","hset_plugins_inventory_search":"پلگ ان تلاش کریں","hset_plugins_inventory_empty":"کوئی پلگ ان اندراج نہیں۔","hset_plugins_disabled":"غیر فعال",
 "hset_presets_hint":"ایجنٹ پری سیٹ طے کرتے ہیں کہ نئی نشستیں کس ماڈل اور سسٹم پرامپٹ سے شروع ہوتی ہیں۔","hset_preset_empty":"کوئی ایجنٹ پری سیٹ نہیں۔","hset_preset_default":"ڈیفالٹ","hset_preset_trust_system":"سسٹم","hset_preset_trust_user":"صارف","hset_preset_broken":"توڑا: %1$s","hset_preset_view":"سورس دیکھیں","hset_preset_set_default":"ڈیفالٹ کے طور پر مقرر کریں","hset_preset_copy":"کاپی…","hset_preset_copy_title":"پری سیٹ کاپی کریں","hset_preset_copy_hint":"ماخذ پری سیٹ کا مواد ایک نئے صارف پری سیٹ میں کاپی کرتا ہے۔","hset_preset_copy_id":"نیا پری سیٹ ID","hset_preset_copy_name":"دکھائی جانے والا نام (اختیاری)","hset_preset_id_invalid":"پری سیٹ ID چھوٹے حروف، اعداد اور ہائیفن استعمال کرتے ہیں، اور ایک حرف یا عدد سے شروع ہوتے ہیں۔","hset_preset_delete_title":"%1$s حذف کریں؟","hset_preset_delete_confirm":"یہ پری سیٹ حذف کر دیتا ہے۔ اسے استعمال کرنے والی نشستیں متاثر نہیں ہوتیں۔","hset_preset_default_saved":"ڈیفالٹ پری سیٹ اپڈیٹ کر دیا گیا۔","hset_preset_copied":"پری سیٹ بن گیا۔","hset_preset_deleted":"پری سیٹ حذف کر دیا گیا۔",
 "hset_val_route_invalid":"راؤٹ ID چھوٹے حروف، اعداد اور ہائیفن استعمال کرتے ہیں، اور ایک حرف سے شروع ہوتے ہیں۔","hset_val_route_taken":"وہ راؤٹ پہلے سے موجود ہے۔","hset_val_base_url_required":"بنیادی URL ضروری ہے۔","hset_val_models_required":"کم از کم ایک ماڈل ضروری ہے۔","hset_val_model_prefix":"ماڈل %1$d: %2$s","hset_val_model_id_required":"ماڈل ID ضروری ہے۔","hset_val_model_id_duplicate":"دوبارہ ماڈل ID۔","hset_val_model_name":"نام خالی نہیں ہو سکتا۔","hset_val_model_context":"کنٹیکسٹ ونڈو ایک مثبت پورا عدد ہونا چاہیے۔","hset_val_model_max_tokens":"زیادہ سے زیادہ ٹوکن ایک مثبت پورا عدد ہونا چاہیے۔","hset_val_api_key_blank":"کلید فیلڈ میں صرف خالی جگہیں ہیں۔","hset_val_api_key_format":"کلید لپٹی ہوئی یا ماحول کی ایک قطار سے چسپی ہوئی لگتی ہے۔ خام کلید چسپاں کریں۔",
}

T["zh-rCN"] = {
 "hset_title":"Harness 设置","hset_entry":"Harness 设置","hset_tab_general":"常规","hset_tab_models":"模型","hset_tab_plugins":"插件","hset_tab_presets":"智能体预设",
 "hset_refused_banner":"此 harness 未授予远程设置访问权限。使用 --allow-privileged-remote 启动它，即可从此设备编辑设置。","hset_unsupported_banner":"此 harness 版本未开放设置平面。","hset_readonly_banner":"设置编辑不可用；仅显示只读值。","hset_edit_available":"此 harness 上可编辑设置。",
 "hset_load_error":"无法读取 harness 设置：%1$s","hset_retry":"重试","hset_saved":"已保存。","hset_removed":"已删除。","hset_save_failed":"保存失败：%1$s","hset_conflict":"设置在此期间已更改。已重新加载最新值；请重试。","hset_not_connected":"未连接到 harness。",
 "hset_general_preset_title":"智能体预设","hset_general_preset_hint":"适用于从现在起开始的会话。","hset_general_permission_title":"权限","hset_general_permission_hint":"新会话的默认权限模式。","hset_general_permission_no_session":"没有打开的会话","hset_general_permission_unknown":"未知","hset_general_locale_title":"语言（Web GUI）","hset_general_locale_system":"系统","hset_general_locale_en":"英语","hset_general_locale_zh":"中文","hset_general_theme_title":"外观（Web GUI）","hset_general_theme_light":"浅色","hset_general_theme_dark":"深色","hset_general_theme_system":"系统","hset_general_open_document":"打开设置文档","hset_general_open_document_hint":"在 harness 计算机上打开用户设置文档。","hset_general_document_opened":"已在主机上打开设置文档。","hset_general_document_unavailable":"此部署无法打开设置文档。",
 "hset_models_empty":"此 harness 版本没有可配置的提供商。","hset_models_active":"已启用","hset_models_custom":"自定义","hset_models_add_provider":"添加提供商","hset_models_add_custom":"添加自定义提供商","hset_models_edit":"编辑","hset_models_remove":"删除","hset_models_remove_model":"删除模型","hset_models_remove_confirm_title":"删除 %1$s？","hset_models_remove_confirm":"这会将该提供商的配置从 harness 设置中删除。","hset_models_key_label":"API 密钥","hset_models_key_configured":"已配置","hset_models_key_missing":"未配置","hset_models_key_hint":"留空以保留已存储的密钥。该值只写入，不再显示。存储为 %1$s。","hset_models_base_url":"基础 URL","hset_models_api_protocol":"协议","hset_models_display_name":"显示名称","hset_models_custom_route":"路由 ID","hset_models_models_label":"模型","hset_models_models_hint_empty":"没有自定义目录：使用内置目录。","hset_models_built_in_catalog":"内置目录","hset_models_count":"%1$d 个模型","hset_models_add_model":"添加模型","hset_models_model_id":"模型 ID","hset_models_model_name":"名称","hset_models_model_context":"上下文窗口","hset_models_model_max_tokens":"最大令牌数","hset_models_discover":"发现模型","hset_models_discover_title":"发现模型","hset_models_discover_hint":"harness 向此端点请求其模型列表。除此草稿的基础 URL 和密钥外，不会向端点发送任何内容。","hset_models_discover_fetch":"获取","hset_models_discover_apply":"使用所选的 %1$d 个模型","hset_models_discover_failed":"发现失败：%1$s","hset_models_discover_none":"端点未返回任何模型。","hset_models_advanced":"高级字段（只读）","hset_models_unknown_ns":"此提供商由一个本应用不编辑的部分配置：%1$s",
 "hset_plugins_configurable":"可配置","hset_plugins_inventory":"清单","hset_plugins_card_shell":"Shell","hset_plugins_shell_timeout":"命令超时（毫秒）","hset_plugins_shell_max_output":"最大输出（字节）","hset_plugins_card_agent_loop":"智能体循环","hset_plugins_agent_loop_max_parallel":"最大并行工具调用","hset_plugins_card_web_search":"网络搜索（DeepSeek）","hset_plugins_web_search_base_url":"基础 URL","hset_plugins_web_search_max_uses":"最大使用次数","hset_plugins_base_value":"默认：%1$s","hset_plugins_other":"其他设置（只读）","hset_plugins_inventory_search":"搜索插件","hset_plugins_inventory_empty":"没有插件条目。","hset_plugins_disabled":"已禁用",
 "hset_presets_hint":"智能体预设配置新会话以哪个模型和系统提示词开始。","hset_preset_empty":"没有智能体预设。","hset_preset_default":"默认","hset_preset_trust_system":"系统","hset_preset_trust_user":"用户","hset_preset_broken":"已损坏：%1$s","hset_preset_view":"查看源码","hset_preset_set_default":"设为默认","hset_preset_copy":"复制…","hset_preset_copy_title":"复制预设","hset_preset_copy_hint":"将源预设的内容复制到新的用户预设。","hset_preset_copy_id":"新预设 ID","hset_preset_copy_name":"显示名称（可选）","hset_preset_id_invalid":"预设 ID 使用小写字母、数字和连字符，并以字母或数字开头。","hset_preset_delete_title":"删除 %1$s？","hset_preset_delete_confirm":"这将删除该预设。使用它的会话不受影响。","hset_preset_default_saved":"默认预设已更新。","hset_preset_copied":"预设已创建。","hset_preset_deleted":"预设已删除。",
 "hset_val_route_invalid":"路由 ID 使用小写字母、数字和连字符，并以字母开头。","hset_val_route_taken":"该路由已存在。","hset_val_base_url_required":"基础 URL 为必填项。","hset_val_models_required":"至少需要一个模型。","hset_val_model_prefix":"模型 %1$d：%2$s","hset_val_model_id_required":"模型 ID 为必填项。","hset_val_model_id_duplicate":"模型 ID 重复。","hset_val_model_name":"名称不能为空。","hset_val_model_context":"上下文窗口必须为正整数。","hset_val_model_max_tokens":"最大令牌数必须为正整数。","hset_val_api_key_blank":"密钥字段只包含空格。","hset_val_api_key_format":"密钥看起来被包裹或从环境变量行粘贴而来。请粘贴原始密钥。",
}

# ---------------------------------------------------------------------------
# Write each locale file.
# ---------------------------------------------------------------------------
def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;").replace("'", "\\'"))

LOCALES = {
    "ar": "values-ar", "bn": "values-bn", "es": "values-es", "fr": "values-fr",
    "hi": "values-hi", "pt": "values-pt", "ru": "values-ru", "th": "values-th",
    "ur": "values-ur", "zh-rCN": "values-zh-rCN",
}

for code, dirname in LOCALES.items():
    path = f"{REPO}/app/src/main/res/{dirname}/strings.xml"
    s = open(path).read()
    d = T[code]
    missing = [k for k in KEYS if k not in d]
    if missing:
        print(f"{code}: MISSING {missing}")
        continue
    block = "\n    <!-- Harness settings (mirrors the web GUI's settings tabs) -->\n"
    for k in KEYS:
        block += f"    <string name=\"{k}\">{esc(d[k])}</string>\n"
    # idempotent: strip any previous hset block
    s2 = re.sub(r"\n    <!-- Harness settings \(mirrors the web GUI's settings tabs\) -->\n(?:    <string name=\"hset_[^\"]+\">.*?</string>\n)+", "\n", s)
    s2 = s2.replace("</resources>", block + "</resources>")
    open(path, "w").write(s2)
    xml.dom.minidom.parse(path)
    print(f"{code}: wrote {len(KEYS)} strings, XML OK")
